### ISSUE TITLE
Needed to add () at the end of require

### ISSUE THREAD

**Issue by Donkfather** [hacknug/tailwindcss-multi-column#2]
Hello,

I had to add `()` at the end of `require` in order to work.

```
plugins:[
   require('tailwindcss-multi-column')()
]
```

Maybe this helps someone. Thank you for the package <3

**Comment by hacknug** [comment]
@Donkfather just pushed a fix. Thanks for the heads up!

**Comment by surjithctly** [comment]
Just tried this plugin and had to add `()` this but no idea why this required since other plugins don't.

**Comment by hacknug** [comment]
> Just tried this plugin and had to add `()` this but no idea why this required since other plugins don't.

Because that's how you call a function. The plugin exports a method you can pass options to and that returns all of the styles generated by the plugin.

The plugin API has changed a lot since 2017. The reason you need to manually call this method is because I didn't bother updating my plugins to use the latest version of the plugin API. Why? Because no one pays for it and they work perfectly fine.

**Comment by surjithctly** [comment]
@hacknug I understand. Just wondered because all official plugins work without that.  
This CSS attribute doesn't seem to be popular so its not worth updating it.

**Comment by hacknug** [comment]
> @hacknug I understand. Just wondered because all official plugins work without that.
> This CSS attribute doesn't seem to be popular so its not worth updating it.

Exactly. Thank you for understanding. Also core will most likely add this at some point like they've been doing with most (if not all) of the features supported by my plugins.
